#!/bin/bash

# READ FIRST BEFORE USING THIS SCRIPT
#
# This script requires gh, git, podman and bash to work properly (dependencies are checked for you).
#
# This script generates a git remote structure described in:
# https://github.com/openshift/kubernetes/blob/master/REBASE.openshift.md#preparing-the-local-repo-clone
# Please check if you have configured the correct remotes, otherwise the script will fail.
#
# The usage is described in /Rebase.openshift.md.

# validate input args --k8s-tag=v1.21.2 --openshift-release=release-4.8 --jira-id=OCPBUGS-91759
k8s_tag=""
openshift_release=""
jira_id=""

usage() {
  echo "Available arguments:"
  echo "  --k8s-tag            (required) Example: --k8s-tag=v1.21.2"
  echo "  --openshift-release  (required) Example: --openshift-release=release-4.8"
  echo "  --jira-id        (optional) Include Jira ticket in PR title: Example: --jira-id=OCPBUGS-1234"
}

for i in "$@"; do
  case $i in
  --k8s-tag=*)
    k8s_tag="${i#*=}"
    shift
    ;;
  --openshift-release=*)
    openshift_release="${i#*=}"
    shift
    ;;
  --jira-id=*)
    jira_id="${i#*=}"
    shift
    ;;
  *)
    usage
    exit 1
    ;;
  esac
done

if [ -z "${k8s_tag}" ]; then
  echo "Required argument missing: --k8s-tag"
  echo ""
  usage
  exit 1
fi

if [ -z "${openshift_release}" ]; then
  echo "Required argument missing: --openshift-release"
  echo ""
  usage
  exit 1
fi

echo "Processed arguments are:"
echo "--k8s_tag=${k8s_tag}"
echo "--openshift_release=${openshift_release}"
echo "--jira_id=${jira_id}"

# prerequisites (check git, podman, ... is present)
if ! command -v git &>/dev/null; then
  echo "git not installed, exiting"
  exit 1
fi

if ! command -v gh &>/dev/null; then
  echo "WARNING: gh not installed, PR creation will be skipped"
fi

if ! command -v podman &>/dev/null; then
  echo "podman not installed, exiting"
  exit 1
fi

# make sure we're in "kubernetes" dir
if [[ $(basename "$PWD") != "kubernetes" ]]; then
  echo "Not in kubernetes dir, exiting"
  exit 1
fi

origin=$(git remote get-url origin)
if [[ "$origin" =~ .*kubernetes/kubernetes.* || "$origin" =~ .*openshift/kubernetes.* ]]; then
  echo "cannot rebase against k/k or o/k! found: ${origin}, exiting"
  exit 1
fi

# fetch remote https://github.com/kubernetes/kubernetes
git remote add upstream https://github.com/kubernetes/kubernetes.git 2>/dev/null || true
git fetch upstream --tags -f
# fetch remote https://github.com/openshift/kubernetes
git remote add openshift https://github.com/JSampsonIV/kubernetes.git 2>/dev/null || true
git fetch openshift

git checkout "$openshift_release" 2>/dev/null || git checkout --track "openshift/$openshift_release"
git pull openshift "$openshift_release"

if [ -z "$(git tag -l "$k8s_tag")" ]; then
    echo "No such tag exists in upstream for: $k8s_tag"
	exit 1
fi
git merge "$k8s_tag"
# shellcheck disable=SC2181
if [ $? -eq 0 ]; then
  echo "No conflicts detected. Automatic merge looks to have succeeded"
else
  echo "Merge conflicts detected. Attempting automated resolution..."
  git status

  # Get list of conflicted files
  conflicted_files=$(git diff --name-only --diff-filter=U)
  unresolvable_files=""

  for f in $conflicted_files; do
    case "$f" in
      go.sum)
        echo "  Resolving $f: accepting upstream (theirs) — regenerated by go mod tidy"
        git checkout --theirs "$f"
        git add "$f"
        ;;
      staging/*/go.mod|staging/*/go.sum)
        echo "  Resolving $f: accepting upstream (theirs) — regenerated by hack/update-vendor.sh"
        git checkout --theirs "$f"
        git add "$f"
        ;;
      vendor/modules.txt)
        echo "  Resolving $f: accepting upstream (theirs) — regenerated by hack/update-vendor.sh"
        git checkout --theirs "$f"
        git add "$f"
        ;;
      go.mod)
        echo "  Resolving $f: merging OpenShift-specific entries with upstream version bumps..."
        # Extract conflict blocks and resolve them
        python3 - "$f" <<'PYEOF'
import sys, re

filepath = sys.argv[1]
with open(filepath, 'r') as fh:
    content = fh.read()

# Known OpenShift-specific module prefixes
openshift_prefixes = (
    'github.com/openshift/',
    'github.com/openshift-eng/',
)

resolved_lines = []
i = 0
lines = content.split('\n')
while i < len(lines):
    line = lines[i]
    if line.startswith('<<<<<<<'):
        # Collect ours block
        ours_lines = []
        theirs_lines = []
        i += 1
        in_ours = True
        while i < len(lines):
            if lines[i].startswith('======='):
                in_ours = False
                i += 1
                continue
            if lines[i].startswith('>>>>>>>'):
                break
            if in_ours:
                ours_lines.append(lines[i])
            else:
                theirs_lines.append(lines[i])
            i += 1

        # Build maps of module -> full line for both sides
        ours_map = {}
        theirs_map = {}
        ours_other = []
        theirs_other = []

        for l in ours_lines:
            m = re.match(r'\s*(\S+)\s+v', l)
            if m:
                ours_map[m.group(1)] = l
            else:
                ours_other.append(l)

        for l in theirs_lines:
            m = re.match(r'\s*(\S+)\s+v', l)
            if m:
                theirs_map[m.group(1)] = l
            else:
                theirs_other.append(l)

        # Merge: keep OpenShift-specific from ours, accept upstream version bumps from theirs
        all_modules = set(list(ours_map.keys()) + list(theirs_map.keys()))
        merged = []
        for mod in sorted(all_modules):
            is_openshift = any(mod.startswith(p) for p in openshift_prefixes)
            if is_openshift:
                # Keep ours for OpenShift-specific
                if mod in ours_map:
                    merged.append(ours_map[mod])
                elif mod in theirs_map:
                    merged.append(theirs_map[mod])
            else:
                # Accept upstream (theirs) version for shared deps
                if mod in theirs_map:
                    merged.append(theirs_map[mod])
                elif mod in ours_map:
                    merged.append(ours_map[mod])

        # Handle non-module lines (like "go 1.xx", toolchain, etc.)
        # Prefer theirs for go/toolchain directives, ours for others
        for l in theirs_other:
            if l.strip().startswith('go ') or l.strip().startswith('toolchain '):
                resolved_lines.append(l)
        for l in ours_other:
            if not (l.strip().startswith('go ') or l.strip().startswith('toolchain ')):
                resolved_lines.append(l)

        resolved_lines.extend(merged)
    else:
        resolved_lines.append(line)
    i += 1

with open(filepath, 'w') as fh:
    fh.write('\n'.join(resolved_lines))

print(f"  go.mod conflicts resolved: kept OpenShift entries, accepted upstream version bumps")
PYEOF
        git add "$f"
        ;;
      *)
        echo "  WARNING: Unresolvable conflict in $f — needs manual review"
        unresolvable_files="$unresolvable_files $f"
        ;;
    esac
  done

  if [ -n "$unresolvable_files" ]; then
    echo "ERROR: Cannot auto-resolve conflicts in:$unresolvable_files"
    echo "Stopping for manual intervention."
    exit 1
  fi

  git commit -m "UPSTREAM: <drop>: automated conflict resolution during rebase"
fi

# openshift-hack/images/hyperkube/Dockerfile.rhel still has FROM pointing to old tag
# we need to remove the prefix "v" from the $k8s_tag to stay compatible
sed -i -E "s/(io.openshift.build.versions=\"kubernetes=)(1.[1-9]+.[1-9]+)/\1${k8s_tag:1}/" \
  openshift-hack/images/hyperkube/Dockerfile.rhel
go_mod_go_ver=$(grep -E 'go 1\.[1-9][0-9]?' go.mod | sed -E 's/go (1\.[1-9][0-9]?)/\1/' | cut -d '.' -f 1,2) # Need to handle mod versions like 1.23 and 1.23.4; our release images only have major.minor
tag=$(grep "^  tag:" .ci-operator.yaml | head -n1 | sed -E 's/.*: (.*)/\1/')

echo "> go mod tidy && hack/update-vendor.sh"
podman run --rm -v "$(pwd):/go/k8s.io/kubernetes:Z" \
  --workdir=/go/k8s.io/kubernetes \
  "registry.ci.openshift.org/openshift/release:$tag" \
  /bin/bash -c "go mod tidy && hack/update-vendor.sh"

# shellcheck disable=SC2181
if [ $? -ne 0 ]; then
  echo "updating the vendor folder failed, is any dependency missing?"
  exit 1
fi

echo "> make clean to remove stale _output directory"
  podman run --rm -v "$(pwd):/go/k8s.io/kubernetes:Z" \
    --workdir=/go/k8s.io/kubernetes \
    "registry.ci.openshift.org/openshift/release:$tag" \
    make clean

podman run --rm -v "$(pwd):/go/k8s.io/kubernetes:Z" \
  --workdir=/go/k8s.io/kubernetes \
  "registry.ci.openshift.org/openshift/release:$tag" \
  make update OS_RUN_WITHOUT_DOCKER=yes

git add -A
git commit -m "UPSTREAM: <drop>: hack/update-vendor.sh, make update and update image"

remote_branch="rebase-$k8s_tag"
git push origin "$openshift_release:$remote_branch"

XY=$(echo "$k8s_tag" | sed -E "s/v(1\.[0-9]+)\.[0-9]+/\1/")
ver=$(echo "$k8s_tag" | sed "s/\.//g")
link="https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-$XY.md#$ver"
if [ -n "${jira_id}" ]; then
  if command -v gh &>/dev/null; then
    XY=$(echo "$k8s_tag" | sed -E "s/v(1\.[0-9]+)\.[0-9]+/\1/")
    ver=$(echo "$k8s_tag" | sed "s/\.//g")
    link="https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-$XY.md#$ver"

    gh pr create \
      --title "$jira_id: Rebase $k8s_tag in $openshift_release" \
      --body "CHANGELOG $link" \
      --base "$openshift_release" \
      --head "$remote_branch"
  fi
fi
